apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: default
type: Opaque
data:
  POSTGRES_DB: <base64_encoded>
  POSTGRES_USER: <base64_encoded>
  POSTGRES_PASSWORD: <base64_encoded>
  
